# Generated by Django 5.0.4 on 2024-05-11 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorID', models.AutoField(primary_key=True, serialize=False, verbose_name='Dcotor ID')),
                ('FullName', models.CharField(max_length=255, verbose_name='Doctor Name')),
                ('Mobile', models.CharField(max_length=155, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='photos/doctor.jpg', null=True, upload_to='doctors/photos/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.AutoField(db_column='PatientID', primary_key=True, serialize=False)),
                ('fileserial', models.CharField(db_column='FileSerial', error_messages='The Patient file number is requiered', max_length=150, null=True, verbose_name='File Number')),
                ('fullname', models.CharField(db_column='FullName', max_length=150, null=True, verbose_name='Patient Name')),
                ('birthdate', models.DateField(db_column='BirthDate', null=True, verbose_name='Birth Date')),
                ('gender', models.BooleanField(db_column='Gender', null=True)),
                ('image', models.ImageField(default='photos/patient.jpg', null=True, upload_to='patients/photos/%y/%m/%d')),
                ('mobile', models.CharField(db_column='Mobile', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=1000, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=150, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
                
                ('reservedBy', models.CharField(blank=True, db_column='ReservedBy', max_length=150, null=True)),
                ('arrivedOn', models.CharField(blank=True, db_column='ArrivedOn', max_length=150, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=2055, null=True)),
                ('sufferedcase', models.CharField(blank=True, db_column='SufferedCase', max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('expectedDate', models.DateField(blank=True, db_column='ExpectedDate', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('latestupdate', models.DateField(blank=True, db_column='LatestUpdate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'verbose_name': 'Patients',
                'ordering': ['-fullname'],
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('SpecialtyID', models.AutoField(primary_key=True, serialize=False)),
                ('SpecialtyNam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisits',
            fields=[
                ('visitid', models.AutoField(db_column='VisitID', primary_key=True, serialize=False)),
                ('visitdate', models.DateTimeField(blank=True, db_column='VisitDate', null=True)),
                ('reasonforvisit', models.TextField(blank=True, db_column='ReasonForVisit', null=True)),
                ('diagnosis', models.TextField(blank=True, db_column='Diagnosis', null=True)),
                ('treatment', models.TextField(blank=True, db_column='Treatment', null=True)),
                ('followup', models.BooleanField(blank=True, db_column='FollowUp', null=True)),
                ('evaluationeegree', models.CharField(blank=True, db_column='EvaluationDegree', max_length=1, null=True)),
                ('createdate', models.DateField(blank=True, db_column='CreateDate', null=True)),
                ('doctorid', models.ForeignKey(blank=True, db_column='DoctorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.doctor')),
                ('patientid', models.ForeignKey(blank=True, db_column='PatientID', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='SpecialtyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.specialties', verbose_name='Speciality Name'),
        ),
    ]
