# Generated by Django 5.0.4 on 2024-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='attendanceDate',
            field=models.DateField(blank=True, db_column='AttendanceDate', null=True),
        ),
    ]
