# Generated by Django 5.0.4 on 2024-05-17 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(db_column='Age', default=0, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')]),
        ),
    ]
