# Generated by Django 5.0.4 on 2024-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_patient_gender_alter_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='rideglass',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], db_column='RideGlass', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='wearingconduct',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], db_column='WearingConduct', max_length=1, null=True),
        ),
    ]
