# Generated by Django 5.0.4 on 2024-05-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_patient_rideglass_patient_wearingconduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('SearchPatients', 'Record a Visit'),),
            },
        ),
    ]
