# Generated by Django 5.0.4 on 2024-05-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_doctorsaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsaudit',
            options={'permissions': (('SearchPatients', 'RecordVisit'),)},
        ),
    ]
