# Generated by Django 5.0.4 on 2024-05-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_doctorsaudit_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorsAudit',
            new_name='PublichDoctorsPerm',
        ),
    ]
