# Generated by Django 5.0.4 on 2024-05-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_rename_doctorsaudit_publichdoctorsperm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublichManagerPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('UploadPatientFile', 'Upload Patients File'), ('LiveReport', 'View Live Report')),
            },
        ),
        migrations.CreateModel(
            name='PublicReceptionistPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('AddNewPatient', 'Add New Patient'), ('UpdatePatinetData', 'Update Patient Data')),
            },
        ),
        migrations.AlterModelOptions(
            name='publichdoctorsperm',
            options={'permissions': (('addNewVisitForPatient', 'Record a Visit'),)},
        ),
    ]
