# Generated by Django 5.0.4 on 2024-05-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_publichmanagerperm_publicreceptionistperm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublichDoctorsPerm',
        ),
        migrations.DeleteModel(
            name='PublichManagerPerm',
        ),
        migrations.DeleteModel(
            name='PublicReceptionistPerm',
        ),
    ]
