# Generated by Django 5.0.4 on 2024-05-25 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_delete_publichdoctorsperm_delete_publichmanagerperm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisits',
            name='patientid',
            field=models.ForeignKey(blank=True, db_column='PatientID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientvisits', to='manager.patient'),
        ),
    ]
