# Generated by Django 5.0.4 on 2024-05-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_patientvisits_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
