# Generated by Django 5.0.4 on 2024-05-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
