# Generated by Django 5.0.7 on 2025-01-11 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_patient_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassficationsOptions',
            fields=[
                ('classifiedID', models.AutoField(db_column='VisitID', primary_key=True, serialize=False)),
                ('classifiedCategory', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, verbose_name='Classified Category')),
                ('optionClassified', models.CharField(max_length=300, verbose_name='Options Classified')),
                ('isActive', models.BooleanField(blank=True, null=True, verbose_name='Is Visiable')),
                ('createdDate', models.DateField(blank=True, null=True, verbose_name='Created Date')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
