# Generated by Django 5.0.7 on 2025-01-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_classficationsoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classficationsoptions',
            name='createdDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
    ]
