# Generated by Django 5.0.7 on 2025-01-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_classficationsoptions_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisits',
            name='classifiedID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.classficationsoptions', verbose_name='Classified Option'),
        ),
    ]
