# Generated by Django 5.0.7 on 2025-01-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_patientvisits_classifiedid'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(blank=True, max_length=100, null=True, verbose_name='City Name')),
                ('isVisible', models.BooleanField(blank=True, null=True)),
                ('createdDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cities',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='confirmationDate',
            field=models.DateField(blank=True, null=True, verbose_name='Confirmation Date'),
        ),
        migrations.AddField(
            model_name='patient',
            name='leadSource',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Youtube', 'Youtube')], max_length=100, null=True, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='patient',
            name='reservationCode',
            field=models.CharField(error_messages='Reservation code is requiered', max_length=150, null=True, verbose_name='Confirmation Code'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.CharField(db_column='FullName', max_length=250, null=True, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.city'),
        ),
    ]
