# Generated by Django 5.0.7 on 2025-01-14 19:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_city_patient_confirmationdate_patient_leadsource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='arrivedOn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='attendanceDate',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Attendance  Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.city', verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='createdby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='expectedDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fileserial',
            field=models.CharField(error_messages='The Patient file number is requiered', max_length=150, null=True, verbose_name='File Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.CharField(max_length=250, null=True, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='latestupdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='leadSource',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Youtube', 'Youtube'), ('Newspaper', 'Newspaper'), ('Friend', 'Friend')], max_length=100, null=True, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='remarks',
            field=models.CharField(blank=True, max_length=2055, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reservedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rideglass',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='Ride Of Glass'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sufferedcase',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updatedby',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='wearingconduct',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='WEaring Conduct'),
        ),
    ]
