# Generated by Django 5.0.7 on 2025-01-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_remove_patient_comingsource_alter_patient_address_and_more'),
    ]
    
    operations = [
      ]

    
