# Generated by Django 5.0.7 on 2025-01-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_remove_patient_comingsource_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='DoctorID',
            new_name='doctorID',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='FullName',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='SpecialtyID',
            new_name='specialtyID',
        ),
        migrations.RenameField(
            model_name='specialties',
            old_name='SpecialtyID',
            new_name='specialtyID',
        ),
        migrations.RenameField(
            model_name='specialties',
            old_name='SpecialtyNam',
            new_name='specialtyNam',
        ),
    ]
