# Generated by Django 5.0.7 on 2025-01-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_rename_doctorid_doctor_doctorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialties',
            old_name='specialtyNam',
            new_name='specialtyName',
        ),
    ]
