# Generated by Django 5.0.7 on 2025-01-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_rename_specialtynam_specialties_specialtyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='createdDate',
            field=models.DateField(blank=True, null=True, verbose_name='created Date'),
        ),
    ]
