# Generated by Django 5.0.7 on 2025-01-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_patient_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='isDeleted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
