# Generated by Django 5.0.7 on 2025-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_patient_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
