# Generated by Django 5.0.7 on 2025-01-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_alter_patient_isdeleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
