# Generated by Django 5.0.7 on 2025-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='createdDate',
            field=models.DateField(auto_now_add=True, verbose_name='Created date'),
        ),
    ]
