# Generated by Django 5.0.7 on 2025-01-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_alter_city_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisits',
            name='visittype',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
