# Generated by Django 5.0.7 on 2025-01-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_patientvisits_visittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offerID', models.AutoField(primary_key=True, serialize=False)),
                ('offerName', models.CharField(blank=True, max_length=350, null=True, verbose_name='Offer Name')),
                ('isVisible', models.BooleanField(blank=True, null=True)),
                ('validFromDate', models.DateField(blank=True, null=True, verbose_name='Valid from')),
                ('validToDate', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='SufferedCases',
            fields=[
                ('caseID', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(blank=True, max_length=350, null=True, verbose_name='Case Name')),
                ('isVisible', models.BooleanField(blank=True, null=True)),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Suffered Case',
                'verbose_name_plural': 'Cases',
            },
        ),
    ]
