# Generated by Django 5.0.7 on 2025-01-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_offers_sufferedcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='offerID',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sufferedcase',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Case'),
        ),
    ]
