# Generated by Django 5.0.7 on 2025-01-23 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_patient_offerid_alter_patient_sufferedcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reservedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserved_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
