# Generated by Django 5.0.7 on 2025-01-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_alter_patient_createdby_alter_patient_reservedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='offerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers_related', to='manager.offers'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sufferedcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='suffered_case', to='manager.sufferedcases'),
        ),
    ]
