# Generated by Django 5.0.7 on 2025-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_alter_patient_offerid_alter_patient_sufferedcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='callDirection',
            field=models.CharField(choices=[('IN', 'INCOMING- Patient Call'), ('OUT', 'OUTGOING - Call Center Call')], default='OUT', max_length=5, verbose_name='Call Direction'),
        ),
    ]
