# Generated by Django 5.0.7 on 2025-01-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_patient_calldirection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='createdby',
            new_name='createdBy',
        ),
    ]
