# Generated by Django 5.0.7 on 2025-01-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_rename_createdby_patient_createdby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sufferedcases',
            old_name='caseID',
            new_name='sufferedcaseID',
        ),
    ]
