# Generated by Django 5.0.7 on 2025-01-23 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_rename_caseid_sufferedcases_sufferedcaseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sufferedcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.sufferedcases'),
        ),
    ]
