# Generated by Django 5.0.7 on 2025-01-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_alter_patient_sufferedcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sufferedcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.sufferedcases', verbose_name='Suffered Case'),
        ),
    ]
