# Generated by Django 5.0.4 on 2025-01-27 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_remove_patient_confirmationdate_calltrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calltrack',
            name='agentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calltrack',
            name='nextFollow',
            field=models.DateField(blank=True, null=True, verbose_name='Next Follow-Up Date'),
        ),
        migrations.AddField(
            model_name='calltrack',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled'), ('Confirmed', 'Confirmed')], max_length=100, null=True, verbose_name='Outcome of Follow-Up'),
        ),
    ]
