# Generated by Django 5.0.4 on 2025-01-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0039_calltrack_agentid_calltrack_nextfollow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUpPrice',
            fields=[
                ('checkupPriceID', models.AutoField(primary_key=True, serialize=False)),
                ('checkupPriceName', models.CharField(blank=True, max_length=350, null=True, verbose_name='check-Up Price')),
                ('isVisible', models.BooleanField(blank=True, null=True)),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'CheckUpPrice',
                'verbose_name_plural': 'CheckUpPrices',
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='leadSource',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Youtube', 'Youtube'), ('Newspaper', 'Newspaper'), ('Friend', 'Friend'), ('Call', 'Call')], max_length=100, null=True, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='patient',
            name='checkUpprice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Check_UpPrice', to='manager.checkupprice'),
        ),
    ]
