# Generated by Django 5.0.7 on 2025-01-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_checkupprice_alter_patient_leadsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='attendanceDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Attendance  Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='createdDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created Date'),
        ),
    ]
