# Generated by Django 5.0.7 on 2025-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_alter_patient_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
    ]
