# Generated by Django 5.0.7 on 2025-01-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_alter_patient_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
