# Generated by Django 5.0.7 on 2025-02-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0045_alter_patient_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCompany',
            fields=[
                ('agentID', models.AutoField(primary_key=True, serialize=False)),
                ('AgentCompany', models.CharField(blank=True, max_length=200, null=True, verbose_name='Agent Company Name')),
                ('isVisible', models.BooleanField(blank=True, null=True)),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Agent-Company',
                'verbose_name_plural': 'Agent-Company',
            },
        ),
        migrations.AlterModelOptions(
            name='checkupprice',
            options={'verbose_name': 'Check-Up Price', 'verbose_name_plural': 'Check-Up Prices'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='leadSource',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Youtube', 'Youtube'), ('Newspaper', 'Newspaper'), ('Friend', 'Friend'), ('Call', 'Call'), ('Instagram', 'Instagram')], max_length=100, null=True, verbose_name='Lead Source'),
        ),
    ]
