# Generated by Django 5.0.7 on 2025-02-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0046_agentcompany_alter_checkupprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='agentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_related', to='manager.agentcompany', verbose_name='Agent/Company'),
        ),
    ]
