# Generated by Django 5.0.7 on 2025-02-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0047_patient_agentid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sufferedcases',
            options={'verbose_name': 'Suffered Case', 'verbose_name_plural': 'Suffered Cases'},
        ),
    ]
