# Generated by Django 5.0.4 on 2025-02-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_alter_sufferedcases_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='DoctorID',
            new_name='doctorID',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='FullName',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='SpecialtyID',
            new_name='specialtyID',
        ),
        migrations.RenameField(
            model_name='specialties',
            old_name='SpecialtyID',
            new_name='specialtyID',
        ),
       
    ]
