# Generated by Django 5.0.4 on 2025-02-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_rename_doctorid_doctor_doctorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialties',
            old_name='SpecialtyNam',
            new_name='specialtyName',
        ),
    ]
