# Generated by Django 5.0.7 on 2025-02-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0050_rename_specialtynam_specialties_specialtyname'),
    ]

    operations = [
        
    ]
