# Generated by Django 5.0.7 on 2025-02-06 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_rename_specialtynam_specialties_specialtyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialtyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manager.specialties', verbose_name='Speciality Name'),
        ),
    ]
