# Generated by Django 5.0.4 on 2025-02-10 07:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_rename_specialtynam_specialties_specialtyname'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='patient',
            name='birthdDate',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='patient',
            name='otherMobile',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')]),
        ),
        migrations.AddField(
            model_name='patient',
            name='reservationType',
            field=models.CharField(choices=[('First Visit', 'First Visit'), ('Follow-up Re-examination', 'Follow-up Re-examination'), ('Follow-up Eye surgery', 'Follow-up Eye surgery')], default='Follow-up Re-examination', max_length=150, verbose_name='Reservation Type'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sufferedcaseByPatient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caseBypatient', to='manager.sufferedcases', verbose_name='Suffered Case by Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='typeFirstVisit',
            field=models.CharField(choices=[('ًWalk-In', 'Walk-In'), ('Referred by someone', 'Referred by someone')], default='Referred by someone', max_length=150, verbose_name='First Visit Type'),
        ),
        migrations.AlterField(
            model_name='agentcompany',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='checkupprice',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='city',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='sufferedcases',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
    ]
