# Generated by Django 5.0.7 on 2025-02-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0052_doctor_specialtyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcompany',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='checkupprice',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='city',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='sufferedcases',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
    ]
