# Generated by Django 5.0.4 on 2025-02-10 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0052_doctor_specialtyid_patient_birthddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialtyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manager.specialties', verbose_name='Speciality Name'),
        ),
    ]
