# Generated by Django 5.0.7 on 2025-02-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0053_doctor_specialtyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birthdDate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='typeFirstVisit',
        ),
        migrations.AddField(
            model_name='patient',
            name='referral',
            field=models.CharField(choices=[('ًW', 'Walk-In'), ('R', 'Referred by someone')], default='R', max_length=150, null=True, verbose_name='Referral'),
        ),
       
        migrations.AlterField(
            model_name='patient',
            name='reservationType',
            field=models.CharField(choices=[('FV', 'First Visit'), ('FX', 'Follow-up Re-examination'), ('FS', 'Follow-up Eye surgery')], default='FX', max_length=150, null=True, verbose_name='Reservation Type'),
        ),
    ]
