# Generated by Django 5.0.7 on 2025-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0054_remove_patient_birthddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mybirthdate',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
    ]
