# Generated by Django 5.0.4 on 2025-02-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0054_alter_patient_reservationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='reservationType',
            field=models.CharField(choices=[('FV', 'First Visit'), ('FX', 'Follow-up Re-examination'), ('FS', 'Follow-up Eye surgery')], default='FX', max_length=150, null=True, verbose_name='Reservation Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='typeFirstVisit',
            field=models.CharField(choices=[('ًW', 'Walk-In'), ('R', 'Referred by someone')], default='R', max_length=150, null=True, verbose_name='First Visit Type'),
        ),
    ]
