# Generated by Django 5.0.4 on 2025-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0055_alter_patient_reservationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='typeFirstVisit',
        ),
        migrations.AddField(
            model_name='patient',
            name='referral',
            field=models.CharField(choices=[('ًW', 'Walk-In'), ('R', 'Referred by someone')], default='R', max_length=150, null=True, verbose_name='Referral'),
        ),
    ]
