# Generated by Django 5.0.7 on 2025-02-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0056_remove_patient_mybirthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
    ]
