# Generated by Django 5.0.7 on 2025-02-11 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_patient_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='callDirection',
            field=models.CharField(choices=[('IN', 'INCOMING- Patient Call'), ('OUT', 'OUTGOING - Call Center Call')], default='OUT', max_length=5, null=True, verbose_name='Call Direction'),
        ),
    ]
