# Generated by Django 5.0.4 on 2025-02-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0058_alter_patient_age_alter_patient_calldirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referral',
            field=models.CharField(choices=[('W', 'Walk-In'), ('R', 'Referred by someone')], default='R', max_length=150, null=True, verbose_name='Referral'),
        ),
    ]
