# Generated by Django 5.0.4 on 2025-02-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0059_alter_patient_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltrack',
            name='trackType',
            field=models.CharField(blank=True, choices=[('CC', 'Call Center'), ('CA', 'Center'), ('MK', 'Marketing')], max_length=100, null=True, verbose_name='Track Type'),
        ),
    ]
