# Generated by Django 5.0.7 on 2025-02-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0060_calltrack_tracktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltrack',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled'), ('Confirmed', 'Confirmed'), ('Re-examination', 'Re-examination'), ('Eye surgery', 'Eye surgery')], max_length=100, null=True, verbose_name='Outcome of Follow-Up'),
        ),
        migrations.AlterField(
            model_name='calltrack',
            name='trackType',
            field=models.CharField(blank=True, choices=[('CC', 'Call Center'), ('CE', 'Center'), ('MK', 'Marketing')], max_length=100, null=True, verbose_name='Track Type'),
        ),
    ]
