# Generated by Django 5.0.4 on 2025-02-17 14:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0062_alter_calltrack_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('conditionName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')], verbose_name='Age'),
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('SELF', 'Self'), ('REL', 'Relative')], max_length=10)),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.medicalcondition')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.patient')),
            ],
        ),
    ]
