# Generated by Django 5.0.4 on 2025-02-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0063_medicalcondition_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='formPrinted',
            field=models.BooleanField(default=False),
        ),
    ]
