# Generated by Django 5.0.4 on 2025-02-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0064_patient_formprinted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='attendanceTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Attendance Time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='attendanceDate',
            field=models.DateField(blank=True, null=True, verbose_name='Attendance Date'),
        ),
    ]
