# Generated by Django 5.0.4 on 2025-02-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0065_patient_attendancetime_alter_patient_attendancedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalConditionData',
            fields=[
                ('conditionID', models.AutoField(primary_key=True, serialize=False)),
                ('conditionName', models.CharField(max_length=100)),
            ],
        ),
    ]
