# Generated by Django 5.0.4 on 2025-02-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0066_medicalconditiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconditiondata',
            name='createdDate',
            field=models.DateField(blank=True, null=True, verbose_name='Created date'),
        ),
        migrations.AddField(
            model_name='medicalconditiondata',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
    ]
