# Generated by Django 5.0.4 on 2025-02-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0067_medicalconditiondata_createddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.medicalconditiondata'),
        ),
        migrations.DeleteModel(
            name='MedicalCondition',
        ),
    ]
