# Generated by Django 5.0.4 on 2025-02-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0068_alter_patientmedicalhistory_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('conditionName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
