# Generated by Django 5.0.4 on 2025-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0069_medicalcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referral',
            field=models.CharField(choices=[('W', 'Walk-In'), ('R', 'Referred by someone')], max_length=150, null=True, verbose_name='Referral'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reservationType',
            field=models.CharField(choices=[('FV', 'First Visit'), ('FX', 'Follow-up Re-examination'), ('FS', 'Follow-up Eye surgery')], default='FV', max_length=150, null=True, verbose_name='Reservation Type'),
        ),
    ]
