# Generated by Django 5.0.7 on 2025-03-20 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0070_alter_patient_referral_alter_patient_reservationtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcompany',
            name='isVisible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='leadSource',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Youtube', 'Youtube'), ('Newspaper', 'Newspaper'), ('Friend', 'Friend'), ('Call', 'Call'), ('Instagram', 'Instagram'), ('Center', 'Center')], max_length=100, null=True, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='referral',
            field=models.CharField(choices=[('W', 'Walk-In'), ('R', 'Referred by someone'), ('F', 'Facebook')], max_length=150, null=True, verbose_name='Referral'),
        ),
        migrations.AlterField(
            model_name='patientvisits',
            name='doctorid',
            field=models.ForeignKey(blank=True, db_column='DoctorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
