# Generated by Django 5.0.7 on 2025-03-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0071_alter_agentcompany_isvisible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classficationsoptions',
            name='classifiedCategory',
            field=models.CharField(choices=[('OK', 'OK'), ('++', '++'), ('Surgery', 'Surgery'), ('6/6', '6/6'), ('Bad', 'Bad')], max_length=20, verbose_name='Classified Category'),
        ),
    ]
