# Generated by Django 5.0.4 on 2025-03-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0072_alter_classficationsoptions_classifiedcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisits',
            name='evaluationeegree',
            field=models.CharField(blank=True, db_column='EvaluationDegree', max_length=20, null=True),
        ),
    ]
