# Generated by Django 5.0.7 on 2025-03-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0073_alter_patientvisits_evaluationeegree'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisits',
            name='updatedDate',
            field=models.DateField(blank=True, db_column='updatedDate', null=True),
        ),
    ]
