# Generated by Django 5.0.7 on 2025-04-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0074_patientvisits_updateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisits',
            name='visitdate',
            field=models.DateField(blank=True, db_column='VisitDate', null=True),
        ),
    ]
