# Generated by Django 5.2 on 2026-01-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0075_alter_patientvisits_visitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fileserial',
            field=models.CharField(default='', error_messages='The Patient file number is requiered', max_length=10, unique=True, verbose_name='File Number'),
        ),
    ]
