# Generated by Django 5.2 on 2026-01-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0076_alter_patient_fileserial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fileserial',
            field=models.CharField(error_messages='The Patient file number is requiered', max_length=150, null=True, verbose_name='File Number'),
        ),
    ]
