# Generated by Django 5.2 on 2026-01-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0079_alter_patient_fileserial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('orgID', models.AutoField(primary_key=True, serialize=False)),
                ('orgName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization Name')),
                ('isVisible', models.BooleanField(blank=True, null=True, verbose_name='Visible')),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='organizationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_related', to='manager.organizations', verbose_name='Organiztaions'),
        ),
    ]
