# Generated by Django 5.2 on 2026-01-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0080_organizations_patient_organizationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='orPrefix',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='orPrefix'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='organizationID',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_related', to='manager.organizations', verbose_name='Organiztaions'),
        ),
    ]
