# Generated by Django 5.2 on 2026-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0081_organizations_orprefix_alter_patient_organizationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fileserial',
            field=models.CharField(error_messages='The Patient file number is requiered', max_length=100, null=True, verbose_name='File Number'),
        ),
    ]
