# Generated by Django 5.2 on 2026-02-07 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0082_alter_patient_fileserial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='orgID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (e.g. +201001711441).', regex='^\\+?\\d{10,15}$')]),
        ),
       
    ]
