# Generated by Django 5.2 on 2026-02-07 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0083_alter_organizations_orgid_alter_patient_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='otherMobile',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (e.g. +201001711441).', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
