# Generated by Django 5.2 on 2026-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0085_alter_patient_updatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='orgID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
