# Generated by Django 5.2 on 2026-02-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0086_alter_organizations_orgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='organizationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_related', to='manager.organizations', verbose_name='Organiztaions'),
        ),
    ]
