# Generated by Django 5.2 on 2026-02-21 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0087_alter_patient_organizationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='otherMobile',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (e.g. +201001711441).', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
