# Generated by Django 5.2 on 2026-02-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0089_userextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slotCharacter',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Desk Character'),
        ),
        migrations.AddField(
            model_name='patient',
            name='slotNumber',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Desk Number'),
        ),
    ]
