# Generated by Django 5.2 on 2026-02-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0090_patient_slotcharacter_patient_slotnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='slotCharacter',
        ),
        migrations.AlterField(
            model_name='patient',
            name='slotNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
