# Generated by Django 5.2 on 2026-03-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0091_remove_patient_slotcharacter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltrack',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled'), ('Re-examination', 'Re-examination'), ('Eye surgery', 'Eye surgery'), ('After surgery', 'After surgery')], max_length=100, null=True, verbose_name='Outcome of Follow-Up'),
        ),
    ]
