# Generated by Django 5.2 on 2026-06-10 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0092_alter_calltrack_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='patients/qr/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
