# Generated by Django 5.2 on 2026-06-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0093_patient_qr_code_patient_qr_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='patient',
            name='reservation_image',
            field=models.ImageField(blank=True, null=True, upload_to='patients/reservations/'),
        ),
    ]
