# Generated by Django 5.2 on 2026-08-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0094_remove_patient_qr_code_patient_reservation_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionResult',
            fields=[
                ('discussionResultID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Discussion Result')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdDate', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Discussion Result',
                'verbose_name_plural': 'Discussion Results',
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('operationTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Operation Type')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdDate', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Operation Type',
                'verbose_name_plural': 'Operation Types',
            },
        ),
        migrations.CreateModel(
            name='PatientDiscussion',
            fields=[
                ('discussionID', models.AutoField(primary_key=True, serialize=False)),
                ('discussionSerial', models.CharField(max_length=150, verbose_name='Discussion Serial')),
                ('specifyDate', models.DateField(blank=True, null=True, verbose_name='Specify Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remainder', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_discussions', to=settings.AUTH_USER_MODEL)),
                ('discussionResult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.discussionresult', verbose_name='Discussion Result')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discussions', to=settings.AUTH_USER_MODEL)),
                ('operationType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.operationtype', verbose_name='Operation Type')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='manager.patient')),
            ],
            options={
                'verbose_name': 'Patient Discussion',
                'verbose_name_plural': 'Patient Discussions',
            },
        ),
    ]
